# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
 release:
   types:
    - published
   tags:
    - ads-console*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Update the Production Tag
      run: git tag ads-console.staging --force && git push origin ads-console.staging --force
